version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: monthly

updates:
  - package-ecosystem: gomod
    directory: /workspace-go
    patterns:
      - "*"
    multi-ecosystem-group: infrastructure

  - package-ecosystem: cargo
    directory: /workspace-rust
    patterns:
      - "*"
    multi-ecosystem-group: infrastructure
