version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: monthly

updates:
  - package-ecosystem: gomod
    directory: /workspace-go
    multi-ecosystem-group: infrastructure
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: /workspace-rust
    multi-ecosystem-group: infrastructure
    groups:
      dependencies:
        patterns:
          - "*"
